/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    testimonials: Testimonial;
    gallery: Gallery;
    jobs: Job;
    scholarships: Scholarship;
    inquiries: Inquiry;
    results: Result;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    gallery: GallerySelect<false> | GallerySelect<true>;
    jobs: JobsSelect<false> | JobsSelect<true>;
    scholarships: ScholarshipsSelect<false> | ScholarshipsSelect<true>;
    inquiries: InquiriesSelect<false> | InquiriesSelect<true>;
    results: ResultsSelect<false> | ResultsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'home-page': HomePage;
    'about-page': AboutPage;
    'contact-page': ContactPage;
    'achievements-page': AchievementsPage;
    'academics-page': AcademicsPage;
    'admission-page': AdmissionPage;
    'career-page': CareerPage;
    'scholarship-page': ScholarshipPage;
  };
  globalsSelect: {
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
    'contact-page': ContactPageSelect<false> | ContactPageSelect<true>;
    'achievements-page': AchievementsPageSelect<false> | AchievementsPageSelect<true>;
    'academics-page': AcademicsPageSelect<false> | AcademicsPageSelect<true>;
    'admission-page': AdmissionPageSelect<false> | AdmissionPageSelect<true>;
    'career-page': CareerPageSelect<false> | CareerPageSelect<true>;
    'scholarship-page': ScholarshipPageSelect<false> | ScholarshipPageSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  quote?: string | null;
  author?: string | null;
  role?: string | null;
  image?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery".
 */
export interface Gallery {
  id: number;
  title?: string | null;
  description?: string | null;
  category?: ('sports' | 'arts' | 'academic' | 'campus' | 'events') | null;
  image?: (number | null) | Media;
  date?: string | null;
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs".
 */
export interface Job {
  id: number;
  title?: string | null;
  department?: ('academic' | 'admin' | 'support' | 'specialized') | null;
  location?: string | null;
  type?: ('full-time' | 'part-time' | 'contract') | null;
  requirements?:
    | {
        point?: string | null;
        id?: string | null;
      }[]
    | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scholarships".
 */
export interface Scholarship {
  id: number;
  title: string;
  category: 'rank' | 'percentage' | 'board';
  standards: string;
  reward?: string | null;
  criteria?: string | null;
  iconName?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries".
 */
export interface Inquiry {
  id: number;
  studentName: string;
  parentName: string;
  email: string;
  phone: string;
  classFor: string;
  message?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "results".
 */
export interface Result {
  id: number;
  year: string;
  category: 'SSC' | 'HSC';
  summaryStats?: {
    schoolResult?: string | null;
    boardResult?: string | null;
  };
  studentResults?:
    | {
        studentName: string;
        percentage: string;
        grade?: string | null;
        id?: string | null;
      }[]
    | null;
  image?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'gallery';
        value: number | Gallery;
      } | null)
    | ({
        relationTo: 'jobs';
        value: number | Job;
      } | null)
    | ({
        relationTo: 'scholarships';
        value: number | Scholarship;
      } | null)
    | ({
        relationTo: 'inquiries';
        value: number | Inquiry;
      } | null)
    | ({
        relationTo: 'results';
        value: number | Result;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  quote?: T;
  author?: T;
  role?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery_select".
 */
export interface GallerySelect<T extends boolean = true> {
  title?: T;
  description?: T;
  category?: T;
  image?: T;
  date?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs_select".
 */
export interface JobsSelect<T extends boolean = true> {
  title?: T;
  department?: T;
  location?: T;
  type?: T;
  requirements?:
    | T
    | {
        point?: T;
        id?: T;
      };
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scholarships_select".
 */
export interface ScholarshipsSelect<T extends boolean = true> {
  title?: T;
  category?: T;
  standards?: T;
  reward?: T;
  criteria?: T;
  iconName?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries_select".
 */
export interface InquiriesSelect<T extends boolean = true> {
  studentName?: T;
  parentName?: T;
  email?: T;
  phone?: T;
  classFor?: T;
  message?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "results_select".
 */
export interface ResultsSelect<T extends boolean = true> {
  year?: T;
  category?: T;
  summaryStats?:
    | T
    | {
        schoolResult?: T;
        boardResult?: T;
      };
  studentResults?:
    | T
    | {
        studentName?: T;
        percentage?: T;
        grade?: T;
        id?: T;
      };
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  heroSlides?:
    | {
        title: string;
        highlightWord?: string | null;
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  scrollCards?:
    | {
        title: string;
        description: string;
        image?: (number | null) | Media;
        buttonText?: string | null;
        id?: string | null;
      }[]
    | null;
  resultsHighlight?:
    | {
        title: string;
        image?: (number | null) | Media;
        yearlyData?:
          | {
              academicYear: string;
              schoolResult: string;
              boardResult: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  contactUs: {
    schoolAddress: {
      street: string;
      city: string;
    };
    primaryContact: {
      phone: string;
    };
    locationInfo: {
      /**
       * Paste the "src" URL from the Google Maps iframe embed code.
       */
      mapEmbedUrl: string;
    };
    responseTime?: {
      admissionResponse?: string | null;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: number;
  hero: {
    badge?: string | null;
    title: string;
    description?: string | null;
  };
  philosophy?: {
    missionTitle?: string | null;
    missionContent?: string | null;
    visionTitle?: string | null;
    visionContent?: string | null;
    acronymValues?:
      | {
          letter?: string | null;
          word?: string | null;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  regulations?: {
    norms?:
      | {
          item?: string | null;
          id?: string | null;
        }[]
      | null;
    rules?:
      | {
          item?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  houseSystem?: {
    description?: string | null;
    houses?:
      | {
          name?: string | null;
          colorName?: string | null;
          motto?: string | null;
          /**
           * e.g. #0000ff
           */
          hexColor?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  leadership?:
    | {
        name: string;
        role: string;
        image?: (number | null) | Media;
        introduction: string;
        message: string;
        gradient?:
          | ('from-amber-500 to-orange-500' | 'from-purple-500 to-pink-500' | 'from-blue-500 to-cyan-500')
          | null;
        id?: string | null;
      }[]
    | null;
  team?:
    | {
        name: string;
        designation: string;
        /**
         * e.g. Primary Teacher, Arts Dept
         */
        category?: string | null;
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  establishedYear?: number | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page".
 */
export interface ContactPage {
  id: number;
  hero?: {
    title?: string | null;
    subtitle?: string | null;
  };
  mainInfo?: {
    emails?:
      | {
          email?: string | null;
          id?: string | null;
        }[]
      | null;
    address?: string | null;
    supportHours?:
      | {
          day?: string | null;
          hours?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  contactNumbers?:
    | {
        department?: string | null;
        number?: string | null;
        ext?: string | null;
        id?: string | null;
      }[]
    | null;
  emergencyContacts?:
    | {
        type?: string | null;
        number?: string | null;
        person?: string | null;
        id?: string | null;
      }[]
    | null;
  transportation?:
    | {
        method?: string | null;
        details?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "achievements-page".
 */
export interface AchievementsPage {
  id: number;
  resultsSection: {
    title: string;
    description?: string | null;
    stats?:
      | {
          iconEmoji?: string | null;
          number: string;
          label: string;
          id?: string | null;
        }[]
      | null;
    results?:
      | {
          image?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  schoolAchievements?: {
    title?: string | null;
    subtitle?: string | null;
    stats?:
      | {
          number: string;
          label: string;
          iconEmoji?: string | null;
          id?: string | null;
        }[]
      | null;
    items?:
      | {
          title: string;
          description?: string | null;
          image?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  studentAchievements?: {
    title?: string | null;
    subtitle?: string | null;
    students?:
      | {
          name: string;
          achievementTitle: string;
          description: string;
          image?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  coCurricular?: {
    title?: string | null;
    description?: string | null;
    events?:
      | {
          title: string;
          description?: string | null;
          date?: string | null;
          location?: string | null;
          category?: ('Science & Technology' | 'Literary' | 'Sports' | 'Cultural' | 'STEM') | null;
          images?:
            | {
                image?: (number | null) | Media;
                id?: string | null;
              }[]
            | null;
          highlights?:
            | {
                text?: string | null;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "academics-page".
 */
export interface AcademicsPage {
  id: number;
  hero: {
    title: string;
    subtitle?: string | null;
  };
  examSchedules?:
    | {
        term: string;
        date: string;
        classes: string;
        status?: ('Upcoming' | 'Ongoing' | 'Completed') | null;
        id?: string | null;
      }[]
    | null;
  upcomingEvents?:
    | {
        title: string;
        date: string;
        time: string;
        venue: string;
        category?: string | null;
        participants?: string | null;
        id?: string | null;
      }[]
    | null;
  ptmSchedules?:
    | {
        Exam: string;
        date: string;
        time: string;
        venue: string;
        'Points To Discuss'?:
          | {
              'point 1'?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admission-page".
 */
export interface AdmissionPage {
  id: number;
  welcomeSection: {
    title: string;
    subtitle?: string | null;
    image?: (number | null) | Media;
  };
  admissionProcess?: {
    title?: string | null;
    steps?:
      | {
          stepNumber: number;
          title: string;
          description?: string | null;
          duration?: string | null;
          iconName?: string | null;
          details?:
            | {
                item?: string | null;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  whyChooseUs?: {
    title?: string | null;
    stats?:
      | {
          label: string;
          value: string;
          iconName?: string | null;
          id?: string | null;
        }[]
      | null;
    features?:
      | {
          iconName?: string | null;
          title: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "career-page".
 */
export interface CareerPage {
  id: number;
  hero?: {
    title?: string | null;
    description?: string | null;
  };
  benefits?:
    | {
        iconName?: string | null;
        title?: string | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scholarship-page".
 */
export interface ScholarshipPage {
  id: number;
  hero?: {
    title?: string | null;
    description?: string | null;
  };
  conditions?:
    | {
        rule?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  heroSlides?:
    | T
    | {
        title?: T;
        highlightWord?: T;
        image?: T;
        id?: T;
      };
  scrollCards?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        buttonText?: T;
        id?: T;
      };
  resultsHighlight?:
    | T
    | {
        title?: T;
        image?: T;
        yearlyData?:
          | T
          | {
              academicYear?: T;
              schoolResult?: T;
              boardResult?: T;
              id?: T;
            };
        id?: T;
      };
  contactUs?:
    | T
    | {
        schoolAddress?:
          | T
          | {
              street?: T;
              city?: T;
            };
        primaryContact?:
          | T
          | {
              phone?: T;
            };
        locationInfo?:
          | T
          | {
              mapEmbedUrl?: T;
            };
        responseTime?:
          | T
          | {
              admissionResponse?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        badge?: T;
        title?: T;
        description?: T;
      };
  philosophy?:
    | T
    | {
        missionTitle?: T;
        missionContent?: T;
        visionTitle?: T;
        visionContent?: T;
        acronymValues?:
          | T
          | {
              letter?: T;
              word?: T;
              description?: T;
              id?: T;
            };
      };
  regulations?:
    | T
    | {
        norms?:
          | T
          | {
              item?: T;
              id?: T;
            };
        rules?:
          | T
          | {
              item?: T;
              id?: T;
            };
      };
  houseSystem?:
    | T
    | {
        description?: T;
        houses?:
          | T
          | {
              name?: T;
              colorName?: T;
              motto?: T;
              hexColor?: T;
              id?: T;
            };
      };
  leadership?:
    | T
    | {
        name?: T;
        role?: T;
        image?: T;
        introduction?: T;
        message?: T;
        gradient?: T;
        id?: T;
      };
  team?:
    | T
    | {
        name?: T;
        designation?: T;
        category?: T;
        image?: T;
        id?: T;
      };
  establishedYear?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page_select".
 */
export interface ContactPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        title?: T;
        subtitle?: T;
      };
  mainInfo?:
    | T
    | {
        emails?:
          | T
          | {
              email?: T;
              id?: T;
            };
        address?: T;
        supportHours?:
          | T
          | {
              day?: T;
              hours?: T;
              id?: T;
            };
      };
  contactNumbers?:
    | T
    | {
        department?: T;
        number?: T;
        ext?: T;
        id?: T;
      };
  emergencyContacts?:
    | T
    | {
        type?: T;
        number?: T;
        person?: T;
        id?: T;
      };
  transportation?:
    | T
    | {
        method?: T;
        details?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "achievements-page_select".
 */
export interface AchievementsPageSelect<T extends boolean = true> {
  resultsSection?:
    | T
    | {
        title?: T;
        description?: T;
        stats?:
          | T
          | {
              iconEmoji?: T;
              number?: T;
              label?: T;
              id?: T;
            };
        results?:
          | T
          | {
              image?: T;
              id?: T;
            };
      };
  schoolAchievements?:
    | T
    | {
        title?: T;
        subtitle?: T;
        stats?:
          | T
          | {
              number?: T;
              label?: T;
              iconEmoji?: T;
              id?: T;
            };
        items?:
          | T
          | {
              title?: T;
              description?: T;
              image?: T;
              id?: T;
            };
      };
  studentAchievements?:
    | T
    | {
        title?: T;
        subtitle?: T;
        students?:
          | T
          | {
              name?: T;
              achievementTitle?: T;
              description?: T;
              image?: T;
              id?: T;
            };
      };
  coCurricular?:
    | T
    | {
        title?: T;
        description?: T;
        events?:
          | T
          | {
              title?: T;
              description?: T;
              date?: T;
              location?: T;
              category?: T;
              images?:
                | T
                | {
                    image?: T;
                    id?: T;
                  };
              highlights?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "academics-page_select".
 */
export interface AcademicsPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        title?: T;
        subtitle?: T;
      };
  examSchedules?:
    | T
    | {
        term?: T;
        date?: T;
        classes?: T;
        status?: T;
        id?: T;
      };
  upcomingEvents?:
    | T
    | {
        title?: T;
        date?: T;
        time?: T;
        venue?: T;
        category?: T;
        participants?: T;
        id?: T;
      };
  ptmSchedules?:
    | T
    | {
        Exam?: T;
        date?: T;
        time?: T;
        venue?: T;
        'Points To Discuss'?:
          | T
          | {
              'point 1'?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admission-page_select".
 */
export interface AdmissionPageSelect<T extends boolean = true> {
  welcomeSection?:
    | T
    | {
        title?: T;
        subtitle?: T;
        image?: T;
      };
  admissionProcess?:
    | T
    | {
        title?: T;
        steps?:
          | T
          | {
              stepNumber?: T;
              title?: T;
              description?: T;
              duration?: T;
              iconName?: T;
              details?:
                | T
                | {
                    item?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  whyChooseUs?:
    | T
    | {
        title?: T;
        stats?:
          | T
          | {
              label?: T;
              value?: T;
              iconName?: T;
              id?: T;
            };
        features?:
          | T
          | {
              iconName?: T;
              title?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "career-page_select".
 */
export interface CareerPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        title?: T;
        description?: T;
      };
  benefits?:
    | T
    | {
        iconName?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scholarship-page_select".
 */
export interface ScholarshipPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        title?: T;
        description?: T;
      };
  conditions?:
    | T
    | {
        rule?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}